<?php

namespace ContainerTA3RMTG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSerializeTestObjFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Factory\SerializeTestObjFactory' shared autowired service.
     *
     * @return \App\Factory\SerializeTestObjFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Factory/SerializeTestObjFactory.php';

        return $container->privates['App\\Factory\\SerializeTestObjFactory'] = new \App\Factory\SerializeTestObjFactory();
    }
}
