<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ1bJ2kF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ1bJ2kF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ1bJ2kF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ1bJ2kF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ1bJ2kF\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q1bJ2kF',
    'container.build_id' => 'e92d7891',
    'container.build_time' => 1692802405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ1bJ2kF');
