<?php

namespace ContainerQ1bJ2kF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3UBtCEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H3UBtCE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H3UBtCE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CoreSerializerController::create' => ['privates', '.service_locator.WmMEGIU', 'get_ServiceLocator_WmMEGIUService', true],
            'App\\Controller\\CoreSerializerController::index' => ['privates', '.service_locator.WmMEGIU', 'get_ServiceLocator_WmMEGIUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CoreSerializerController:create' => ['privates', '.service_locator.WmMEGIU', 'get_ServiceLocator_WmMEGIUService', true],
            'App\\Controller\\CoreSerializerController:index' => ['privates', '.service_locator.WmMEGIU', 'get_ServiceLocator_WmMEGIUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CoreSerializerController::create' => '?',
            'App\\Controller\\CoreSerializerController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CoreSerializerController:create' => '?',
            'App\\Controller\\CoreSerializerController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
